// cicd_bitbucket.go — BitBucket Pipelines YAML generator (C5, T3-T7, T17, T19).
//
// Mirrors generateGitHub / generateGitLab in cicd.go. Split into its own file
// only because cicd.go is already over 450 lines.

package cicd

import (
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

//go:embed bitbucket/templates/*.yaml
var bitbucketTemplates embed.FS

// generateBitbucket renders a `bitbucket-pipelines.yml` for the given mode.
// The canonical output path is the repo-root file; Bitbucket only reads from
// this single location.
func generateBitbucket(opts Options) (string, string, error) {
	var b strings.Builder

	workflowName := modeLabel(opts.Mode)
	image := detectImage(".", opts)
	overlay := loadTemplateOverlay(image)

	fmt.Fprintf(&b, `# R1 CI — %s
# Generated by r1 cicd --provider bitbucket --mode %s
# Docs: https://github.com/RelayOne/r1-agent/docs/integrations/bitbucket-pipelines.md
#
# Required workspace variables (Repository or Workspace settings → Pipelines → Variables):
#   ANTHROPIC_API_KEY    — Anthropic API key for R1 (secured)
#   R1_API_TOKEN         — fallback R1 token when OIDC is unavailable (secured)
#   R1_AUDIT_ENDPOINT    — optional, A3 audit endpoint
#
# OIDC: every step sets `+"`oidc: true`"+` so $BITBUCKET_STEP_OIDC_TOKEN is
# populated for the in-step OIDC exchange (auth.go).

image: %s

`, workflowName, opts.Mode, image)

	if overlay != "" {
		b.WriteString(overlay)
		b.WriteString("\n")
	}

	fmt.Fprintf(&b, "pipelines:\n%s\n", bitbucketTrigger(opts))

	return b.String(), "bitbucket-pipelines.yml", nil
}

// bitbucketTrigger returns the YAML map under `pipelines:` for the active
// mode. Indentation is two spaces (one indent level inside `pipelines:`).
func bitbucketTrigger(opts Options) string {
	step := bitbucketJobStep(opts)
	switch opts.Mode {
	case ModeReview:
		return fmt.Sprintf(`  pull-requests:
    '**':
%s`, step)
	case ModeAutoFix:
		return fmt.Sprintf(`  branches:
    %s:
%s
  pull-requests:
    '**':
%s`, opts.Branch, step, step)
	default: // mission
		return fmt.Sprintf(`  custom:
    r1-mission:
%s`, step)
	}
}

// bitbucketJobStep emits the `- step:` block for the active mode.
func bitbucketJobStep(opts Options) string {
	switch opts.Mode {
	case ModeReview:
		return bitbucketStepBlock(opts, "R1 code review",
			[]string{
				`r1 review --policy "$R1_POLICY" --pr-id "$BITBUCKET_PR_ID" --output bitbucket-comment`,
			})
	case ModeAutoFix:
		return bitbucketStepBlock(opts, "R1 auto-fix",
			[]string{
				`r1 scan-repair --policy "$R1_POLICY" --auto-commit --push-fixes`,
			})
	default: // mission
		return bitbucketStepBlock(opts, "R1 mission runner",
			[]string{
				fmt.Sprintf(`PLAN="${PLAN:-%s}"`, opts.PlanFile),
				fmt.Sprintf(`r1 build "$PLAN" --policy "$R1_POLICY" --workers %d --open-pr`, opts.Workers),
			})
	}
}

// bitbucketStepBlock emits a fully-formed `- step:` block with the canonical
// before-script, the supplied script lines, and the canonical artifacts +
// caches + oidc settings.
func bitbucketStepBlock(opts Options, name string, scriptLines []string) string {
	var sb strings.Builder
	sb.WriteString("      - step:\n")
	fmt.Fprintf(&sb, "          name: \"%s\"\n", name)
	fmt.Fprintf(&sb, "          image: %s\n", detectImage(".", opts))
	sb.WriteString("          oidc: true\n")
	sb.WriteString("          caches:\n")
	for _, c := range bitbucketCachesFor(detectImage(".", opts)) {
		fmt.Fprintf(&sb, "            - %s\n", c)
	}
	sb.WriteString("          script:\n")
	sb.WriteString("            - export R1_POLICY=\"${R1_POLICY:-")
	sb.WriteString(opts.PolicyPath)
	sb.WriteString("}\"\n")
	sb.WriteString("            - curl -fsSL https://github.com/RelayOne/r1-agent/releases/download/")
	sb.WriteString(opts.R1Version)
	sb.WriteString("/install.sh | bash\n")
	sb.WriteString("            - export PATH=\"$HOME/.r1/bin:$PATH\"\n")
	for _, line := range scriptLines {
		fmt.Fprintf(&sb, "            - %s\n", line)
	}
	sb.WriteString("          artifacts:\n")
	for _, glob := range []string{
		"tracebundles/**/*.tar.zst",
		"audit-reports/**/*.json",
		"r1-review.json",
		"r1-mission.log",
	} {
		fmt.Fprintf(&sb, "            - %s\n", glob)
	}
	// Strip the trailing newline for cleaner concatenation.
	return strings.TrimRight(sb.String(), "\n")
}

// detectImage picks a Docker image based on the workspace directory's project
// fingerprint. opts.NodeLabel overrides the auto-detection (it doubles as the
// Bitbucket image, same as for the GitLab adapter).
func detectImage(workspaceDir string, opts Options) string {
	if opts.NodeLabel != "" {
		return opts.NodeLabel
	}
	exists := func(name string) bool {
		_, err := os.Stat(filepath.Join(workspaceDir, name))
		return err == nil
	}
	switch {
	case exists("go.mod"):
		return "golang:1.22-bookworm"
	case exists("package.json"):
		return "node:20-bookworm"
	case exists("pyproject.toml"), exists("requirements.txt"):
		return "python:3.12-bookworm"
	default:
		return "atlassian/default-image:5"
	}
}

// bitbucketCachesFor returns the cache keys appropriate for an image.
func bitbucketCachesFor(image string) []string {
	switch {
	case strings.HasPrefix(image, "golang"):
		return []string{"gomod"}
	case strings.HasPrefix(image, "node"):
		return []string{"nodemod"}
	case strings.HasPrefix(image, "python"):
		return []string{"pip"}
	default:
		return []string{"r1"}
	}
}

// loadTemplateOverlay reads the per-language definitions block from the
// embedded template that matches the image. Returns "" when no overlay
// exists. The overlay supplies the `definitions.caches.*` block referenced by
// the step `caches:` list.
func loadTemplateOverlay(image string) string {
	var fname string
	switch {
	case strings.HasPrefix(image, "golang"):
		fname = "go.yaml"
	case strings.HasPrefix(image, "node"):
		fname = "node.yaml"
	case strings.HasPrefix(image, "python"):
		fname = "python.yaml"
	default:
		fname = "generic.yaml"
	}
	body, err := bitbucketTemplates.ReadFile("bitbucket/templates/" + fname)
	if err != nil {
		return ""
	}
	// Strip the `before-script-snippet:` block — it's an internal marker, not
	// part of the rendered Bitbucket schema. The script body itself is
	// emitted directly in bitbucketStepBlock as needed.
	out := string(body)
	if idx := strings.Index(out, "before-script-snippet:"); idx >= 0 {
		out = out[:idx]
	}
	return strings.TrimRight(out, "\n ")
}
