// Mission-aware prompt templates for each phase of the mission lifecycle.
//
// These templates inject mission context (criteria, gaps, research, handoffs)
// into the prompts that agents receive. They ensure agents understand:
//   - What the mission is trying to accomplish (intent)
//   - What acceptance criteria must be satisfied
//   - What gaps remain from prior validation
//   - What previous agents accomplished (handoff history)
//   - What research has been gathered
//
// Each phase prompt follows the self-reflective loop pattern established
// in the existing Stoke prompts: think → research → verify → act.
package prompts

import (
	"fmt"
	"strings"
)

// MissionContext is the structured context injected into mission-aware prompts.
// Generated by the mission ContextBuilder.
type MissionContext struct {
	MissionID      string   // mission identifier
	Title          string   // short mission name
	Intent         string   // full user intent
	Phase          string   // current lifecycle phase
	CriteriaBlock  string   // formatted criteria checklist
	GapsBlock      string   // formatted open gaps
	ResearchBlock  string   // formatted research findings
	HandoffBlock   string   // formatted handoff history
	StatusBlock    string   // convergence status summary
	PriorContext   string   // any additional context from prior executions

	// Project type information for conditional prompt sections
	HasFrontend   bool   // true if project includes UI components
	UIFramework   string // e.g. "react", "vue", "svelte", "angular"
	TestFramework string // e.g. "jest", "vitest", "playwright"
	HasStorybook  bool   // true if Storybook detected
}

// BuildMissionResearchPrompt generates the prompt for the Researching phase.
// The agent must gather information needed to plan the implementation.
func BuildMissionResearchPrompt(ctx MissionContext) string {
	var b strings.Builder

	fmt.Fprintf(&b, `You are a research agent working on mission "%s".

## Mission
**Title:** %s
**Intent:** %s

`, ctx.MissionID, ctx.Title, ctx.Intent)

	if ctx.CriteriaBlock != "" {
		fmt.Fprintf(&b, "%s\n", ctx.CriteriaBlock)
	}

	b.WriteString(`## Your Task: Research Phase

Gather all information needed to plan and implement this mission. Follow this process:

### Step 1: Analyze the intent
Break down the user's intent into specific technical requirements. For each requirement:
- What needs to exist that doesn't today?
- What existing code needs to change?
- What interfaces, contracts, or APIs are affected?

### Step 2: Research the codebase
For each requirement, search the codebase to understand:
- Existing patterns and conventions
- Related code that this change touches
- Test infrastructure available
- Build and deployment constraints

### Step 3: Research external knowledge
For any requirement where you lack domain expertise:
- Search for authoritative documentation
- Find best practices and common pitfalls
- Identify security implications
- Look for prior art in similar systems

### Step 4: Completeness check
Ask yourself: "Do I have enough information to write a detailed, accurate implementation plan?"
If NO: identify gaps and continue researching.
If YES: produce your research summary.

### Output
Produce a structured research document with:
- **Requirements breakdown**: numbered list of specific technical requirements
- **Codebase findings**: relevant files, patterns, and constraints
- **External research**: domain knowledge, best practices, security notes
- **Knowledge gaps**: anything still uncertain (be honest)
- **Recommended approach**: high-level strategy based on research

`)

	if ctx.ResearchBlock != "" {
		fmt.Fprintf(&b, "## Prior Research\n%s\n", ctx.ResearchBlock)
	}
	if ctx.HandoffBlock != "" {
		fmt.Fprintf(&b, "## Handoff Context\n%s\n", ctx.HandoffBlock)
	}

	return b.String()
}

// BuildMissionPlanPrompt generates the prompt for the Planning phase.
// The agent must create a detailed implementation plan with verification criteria.
func BuildMissionPlanPrompt(ctx MissionContext) string {
	var b strings.Builder

	fmt.Fprintf(&b, `You are a planning agent working on mission "%s".

## Mission
**Title:** %s
**Intent:** %s

`, ctx.MissionID, ctx.Title, ctx.Intent)

	if ctx.CriteriaBlock != "" {
		fmt.Fprintf(&b, "%s\n", ctx.CriteriaBlock)
	}
	if ctx.StatusBlock != "" {
		fmt.Fprintf(&b, "%s\n", ctx.StatusBlock)
	}

	b.WriteString(`## Your Task: Planning Phase

Create a detailed implementation plan. Every acceptance criterion must map to specific implementation tasks.

### Requirements
1. Each task must specify: files to modify, what changes, why this approach
2. Each task must include verification items (testable assertions)
3. Tasks must be ordered by dependency (what must come first)
4. Tasks must not overlap in file scope (for parallel execution)
5. Every acceptance criterion must be covered by at least one task
6. Include a "ship blockers" section — what absolutely must work

### Output Format
Produce a JSON plan:
` + "```json" + `
{
  "tasks": [
    {
      "id": "t-1",
      "description": "...",
      "files": ["path/to/file.go"],
      "changes": "...",
      "rationale": "...",
      "depends_on": [],
      "criteria_covered": ["c-1"],
      "verification": [
        "GET /api/auth returns 200 with valid JWT",
        "GET /api/auth returns 401 without token"
      ]
    }
  ],
  "ship_blockers": [
    "All tests pass",
    "No TODO comments in committed code"
  ]
}
` + "```" + `

`)

	if ctx.ResearchBlock != "" {
		fmt.Fprintf(&b, "## Research Findings\n%s\n", ctx.ResearchBlock)
	}
	if ctx.GapsBlock != "" {
		fmt.Fprintf(&b, "## Known Gaps (from prior validation)\n%s\n", ctx.GapsBlock)
	}
	if ctx.HandoffBlock != "" {
		fmt.Fprintf(&b, "## Handoff Context\n%s\n", ctx.HandoffBlock)
	}

	return b.String()
}

// BuildMissionExecutePrompt generates the prompt for the Executing phase.
// The agent must implement the plan and satisfy acceptance criteria.
func BuildMissionExecutePrompt(ctx MissionContext, taskDescription string, verification []string) string {
	var b strings.Builder

	fmt.Fprintf(&b, `You are an implementation agent working on mission "%s".

## Mission
**Title:** %s
**Intent:** %s

`, ctx.MissionID, ctx.Title, ctx.Intent)

	if ctx.CriteriaBlock != "" {
		fmt.Fprintf(&b, "%s\n", ctx.CriteriaBlock)
	}
	if ctx.StatusBlock != "" {
		fmt.Fprintf(&b, "%s\n", ctx.StatusBlock)
	}

	fmt.Fprintf(&b, "## Your Task\n%s\n\n", taskDescription)

	if len(verification) > 0 {
		b.WriteString("## Verification Requirements\nYour work MUST satisfy these:\n")
		for _, v := range verification {
			fmt.Fprintf(&b, "- [ ] %s\n", v)
		}
		b.WriteString("\n")
	}

	b.WriteString(`## Rules
1. Implement FULLY. No stubs, no TODOs, no "implement later" comments.
2. Write real tests that verify behavior, not smoke tests.
3. Follow existing codebase patterns and conventions.
4. Do NOT run git add, git commit, or git push — Stoke handles that.
5. Run build and test commands to verify your work before declaring done.
6. If you encounter a blocker you cannot resolve, explain it clearly — do not silently skip it.

`)

	if ctx.HasFrontend {
		b.WriteString(`## UX Quality Rules (REQUIRED — this is a frontend project)
These are NOT optional. The convergence validator will reject your work if these are violated:
- Every image MUST have alt text. Every form input MUST have a label.
- Every interactive element MUST be keyboard-accessible (use semantic HTML: button, a, input).
- Layout MUST be responsive — test at mobile (320px), tablet (768px), and desktop widths.
- Every async operation MUST have loading AND error states — no blank screens.
- Use CSS variables or design tokens for colors — no hardcoded hex in inline styles.
- Handle empty states explicitly — show helpful messages when there's no data.
- Focus indicators must be visible for keyboard navigation.
`)
		if ctx.UIFramework == "react" {
			b.WriteString(`- Wrap app root in ErrorBoundary with user-friendly fallback UI.
- Use key props on every list item rendered via .map().
- No dangerouslySetInnerHTML without DOMPurify sanitization.
`)
		}
		if ctx.HasStorybook {
			b.WriteString("- Every new component MUST have a Storybook story covering its variants.\n")
		}
		if ctx.TestFramework != "" {
			fmt.Fprintf(&b, "- Write component tests using %s — test user interactions, not implementation details.\n", ctx.TestFramework)
		}
		b.WriteString("\n")
	}

	if ctx.GapsBlock != "" {
		fmt.Fprintf(&b, "## Open Gaps (must address)\n%s\n", ctx.GapsBlock)
	}
	if ctx.ResearchBlock != "" {
		fmt.Fprintf(&b, "## Research Context\n%s\n", ctx.ResearchBlock)
	}
	if ctx.HandoffBlock != "" {
		fmt.Fprintf(&b, "## Prior Agent Context\n%s\n", ctx.HandoffBlock)
	}
	if ctx.PriorContext != "" {
		fmt.Fprintf(&b, "## Additional Context\n%s\n", ctx.PriorContext)
	}

	return b.String()
}

// BuildMissionValidatePrompt generates the prompt for the Validating phase.
// The agent must adversarially check whether the work is actually complete.
func BuildMissionValidatePrompt(ctx MissionContext) string {
	var b strings.Builder

	fmt.Fprintf(&b, `You are a validation agent reviewing mission "%s".

## Mission
**Title:** %s
**Intent:** %s

`, ctx.MissionID, ctx.Title, ctx.Intent)

	if ctx.CriteriaBlock != "" {
		fmt.Fprintf(&b, "%s\n", ctx.CriteriaBlock)
	}
	if ctx.StatusBlock != "" {
		fmt.Fprintf(&b, "%s\n", ctx.StatusBlock)
	}

	b.WriteString(`## Your Task: Adversarial Validation

You are NOT here to confirm the work is good. You are here to find reasons it ISN'T done.
Your default assumption is: THE WORK IS NOT DONE. Prove yourself wrong with evidence.

### The 5 Convergence Gates (ALL must be TRUE)

**Gate 1: User intent is fully satisfied**
For each acceptance criterion, find PROOF it's met. Not "it looks right" — show the
test, show the assertion, show the output. No proof = not met.

**Gate 2: Everything works — the ENTIRE system, not just what was changed**
Build passes. ALL tests pass. Lint passes. Not just the tests for the changed code —
ALL tests in the entire repository. Pre-existing failures are YOUR problem too.

**Gate 3: Engineering standards, security, and optimization are exhaustive**
- No TODOs, FIXMEs, HACKs, stubs, placeholders, or "implement later" comments anywhere
- No panics in production code
- No ignored errors
- No SQL injection, command injection, path traversal, XSS, hardcoded secrets
- No debug print statements (use structured logging)
- No type safety bypasses (@ts-ignore, nolint, etc.)
- Every function has proper error handling
- Tests verify BEHAVIOR, not just compilation — tautological tests are failures
- Edge cases handled: nil inputs, empty strings, concurrent access, error paths

`)

	if ctx.HasFrontend {
		b.WriteString(`**Gate 3a: UX quality — THIS IS A FRONTEND PROJECT, these are mandatory**
- ALL images have alt attributes (WCAG 2.1 Level A)
- ALL form inputs have associated labels or aria-label
- ALL interactive elements are keyboard-accessible (no onClick on div without role/tabIndex)
- Focus indicators are never removed without replacement (outline:none requires :focus-visible)
- Responsive viewport meta tag present in HTML documents
- Stylesheets use media queries and responsive units — layout works on mobile/tablet/desktop
- Data-fetching components have loading states AND error states — no blank screens
- No dangerouslySetInnerHTML without sanitization (XSS vector)
- List rendering uses key props (React .map() without key = render bugs)
- No hardcoded colors in inline styles — use CSS variables or design tokens for theming
- UI is consistent: spacing, typography, color palette follow a design system
- Forms have client-side validation with clear error messages
- Empty states are handled — don't show blank pages when there's no data
`)
		if ctx.UIFramework == "react" {
			b.WriteString("- React apps have ErrorBoundary at the root — render errors show fallback, not blank page\n")
		}
		if ctx.HasStorybook {
			b.WriteString("- Every component has Storybook stories covering its variants\n")
		}
	}

	b.WriteString(`

**Gate 4: Everything was researched and confirmed accurate**
No guesses. No hallucinated APIs. Every external dependency, every algorithm choice,
every security decision must be based on verified knowledge.

**Gate 5: Everything in the repo that was started is finished**
Look at the ENTIRE repository, not just the files that were changed. If there are
scaffolded features, half-built modules, or partially implemented code ANYWHERE in
the repo, those are failures. If someone started something, it must be finished.

### IMPORTANT: Do not rationalize
Models will find reasons to say "done" — architecture decisions, pre-existing issues,
"out of scope" — ignore those impulses. If something can be fixed or improved, it's
not done. The question is not "is this acceptable?" The question is "is there ANYTHING
else that could be done to make this better?" If yes, it's incomplete.

### CRITICAL: "Exists" is not "Works"
The most dangerous failure mode is declaring something done because the CODE exists
without verifying it's WIRED, INVOKED, and TESTED end-to-end. Specifically check:
- New types/functions declared → are they actually called from the integration layer?
- New config fields added → does any code read them and change behavior?
- New rules/checks added → are they registered in the default set AND run during validation?
- New parameters accepted → do callers actually pass meaningful values?
- New conditional logic → do tests exercise BOTH the true AND false branches?
Dead code that looks complete is WORSE than missing code because it creates false confidence.

### Output Format
Return JSON:
` + "```json" + `
{
  "verdict": "complete" | "incomplete",
  "score": 0.0-1.0,
  "criteria_status": [
    {"id": "c-1", "satisfied": true, "evidence": "jwt_test.go:42 verifies token generation"},
    {"id": "c-2", "satisfied": false, "reason": "no test for invalid token rejection"}
  ],
  "gaps": [
    {
      "category": "test|code|security|completeness|optimization|consistency",
      "severity": "blocking",
      "file": "path/to/file.go",
      "line": 42,
      "description": "...",
      "suggestion": "..."
    }
  ],
  "reasoning": "Overall assessment — be specific about what's missing"
}
` + "```" + `

### Rules
- Do NOT modify any files. Read only.
- Do NOT run git commands.
- Be specific: file paths, line numbers, concrete evidence.
- "Looks good" is NOT evidence. Show the test, show the assertion, show the output.
- When in doubt, flag it. False positives are better than missed issues.
- ALL gap severities should be "blocking" — there is no "nice to have."

`)

	if ctx.GapsBlock != "" {
		fmt.Fprintf(&b, "## Previously Identified Gaps\nVerify these are resolved:\n%s\n", ctx.GapsBlock)
	}

	return b.String()
}

// BuildMissionConsensusPrompt generates the prompt for the consensus check.
// A different model reviews the work independently and tries to DISPROVE
// that the work is complete. This is not rubber-stamping — it's adversarial.
func BuildMissionConsensusPrompt(ctx MissionContext, validationReport string) string {
	var b strings.Builder

	fmt.Fprintf(&b, `You are an independent adversarial reviewer for mission "%s".

## Mission
**Title:** %s
**Intent:** %s

`, ctx.MissionID, ctx.Title, ctx.Intent)

	if ctx.CriteriaBlock != "" {
		fmt.Fprintf(&b, "%s\n", ctx.CriteriaBlock)
	}

	fmt.Fprintf(&b, `## Prior Validation Report (from another model)
%s

## Your Task: Try to DISPROVE Completeness

Your job is NOT to confirm the work is done. Your job is to find what's missing.
Assume the prior validator was too lenient. Assume the implementing agent cut corners.
Your default stance: THIS IS NOT DONE YET.

### Step 1: Independent verification
DO NOT trust the prior validator's findings. Check the code yourself:
- Read every file mentioned in the criteria
- Run through each acceptance criterion independently
- Look for things the validator missed or was too generous about

### Step 2: Challenge with these questions
For each "complete" verdict, ask yourself:
- "Is this REALLY completely done, or is there more we could do?"
- "Why can't we just make the decision for best quality and get this done?"
- "Is this an excuse to stop working, or is it genuinely finished?"
- "Would I ship this to a paying customer right now with confidence?"
- "If I showed this to the most demanding code reviewer I know, what would they say?"

### Step 3: Look beyond what was asked
The entire system must work, not just the parts that were changed:
- Are there pre-existing failures that should be fixed?
- Are there scaffolded or partially-implemented features elsewhere?
- Could the architecture be cleaner?
- Are there performance issues?
- Is error handling comprehensive everywhere, not just in new code?
- If there is a UI: is it accessible? Responsive? Does it handle loading/error/empty states?
- Would a real user on a phone, using a screen reader, or on a slow connection have a good experience?
- Are focus indicators visible? Can every interactive element be reached by keyboard?

### CRITICAL: Anti-rationalization protocol
Models will generate sophisticated-sounding reasons to mark work as "done":
- "This is an architecture decision" → But is it the RIGHT decision? Can we improve it?
- "This is pre-existing" → So? Fix it. The system should be 100%%.
- "This is out of scope" → Nothing is out of scope for quality.
- "This would be too much effort" → Effort is not a valid excuse.
- "This is a minor issue" → There are no minor issues. Fix everything.
- "The code exists" → Is it WIRED? Is it CALLED? Does any test prove it runs?
- "I added the function" → Who invokes it? Trace the call chain from entry point to function.
- "The rules are defined" → Are they registered? Enabled? Exercised in tests?

Dead code that looks complete is the most dangerous form of incompleteness.
If you catch yourself making ANY of these rationalizations, flag the item as incomplete.

### Output Format
Return JSON:
`+"```json"+`
{
  "verdict": "complete" | "incomplete" | "reject",
  "agree_with_validator": true | false,
  "missed_by_validator": [
    {
      "category": "...",
      "severity": "blocking",
      "file": "...",
      "description": "...",
      "suggestion": "..."
    }
  ],
  "challenges": [
    "Question I asked myself and the honest answer"
  ],
  "reasoning": "Detailed reasoning for my verdict — if 'complete', explain why every challenge was genuinely answered"
}
`+"```"+`

### Rules
- Do NOT modify any files. Read only.
- Do NOT rubber-stamp. If you can't find anything wrong, look harder.
- ALL severities are "blocking" — there is no "nice to have."
- Only vote "complete" if you genuinely cannot find a single thing to improve.

`, validationReport)

	return b.String()
}
