package wizard

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/RelayOne/r1/internal/r1dir"
	"gopkg.in/yaml.v3"
)

// writeOutput creates the .stoke/ directory, writes config.yaml, copies skill
// files from the library, and writes the rationale document.
func writeOutput(root string, r *WizardResult) error {
	stokeDir := r1dir.JoinFor(root)
	if err := os.MkdirAll(stokeDir, 0755); err != nil {
		return err
	}

	// Write config.yaml
	cfgPath := filepath.Join(stokeDir, "config.yaml")
	data, err := yaml.Marshal(r.Config)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	header := []byte("# Generated by stoke wizard\n# https://github.com/RelayOne/r1\n\n")
	if err := os.WriteFile(cfgPath, append(header, data...), 0644); err != nil { // #nosec G306 -- wizard-generated config consumed by user tooling; 0644 is appropriate.
		return fmt.Errorf("write config: %w", err)
	}

	// Copy selected skills from the library to .stoke/skills/
	skillsDir := filepath.Join(stokeDir, "skills")
	if err := os.MkdirAll(skillsDir, 0755); err != nil {
		return err
	}
	if err := copySkills(r.Skills, skillsDir); err != nil {
		fmt.Fprintf(os.Stderr, "[wizard] copy skills: %v\n", err)
	}

	// Write rationale document
	rationalePath := filepath.Join(stokeDir, "wizard-rationale.md")
	return os.WriteFile(rationalePath, []byte(renderDetailedRationale(r)), 0644) // #nosec G306 -- wizard-generated config consumed by user tooling; 0644 is appropriate.
}

// copySkills copies skill files from library locations to the project .stoke/skills/.
func copySkills(names []string, destDir string) error {
	home, _ := os.UserHomeDir()
	libraryDirs := []string{
		r1dir.JoinFor(home, "skills"),
	}
	for _, name := range names {
		for _, lib := range libraryDirs {
			src := filepath.Join(lib, name)
			if _, err := os.Stat(src); err == nil {
				dst := filepath.Join(destDir, name)
				if err := copyDir(src, dst); err != nil {
					return fmt.Errorf("copy %s: %w", name, err)
				}
				break
			}
		}
	}
	return nil
}

func copyDir(src, dst string) error {
	if err := os.MkdirAll(dst, 0755); err != nil {
		return err
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}
	for _, e := range entries {
		srcPath := filepath.Join(src, e.Name())
		dstPath := filepath.Join(dst, e.Name())
		if e.IsDir() {
			if err := copyDir(srcPath, dstPath); err != nil {
				return err
			}
		} else {
			data, err := os.ReadFile(srcPath)
			if err != nil {
				return err
			}
			if err := os.WriteFile(dstPath, data, 0644); err != nil { // #nosec G306 -- wizard-generated config consumed by user tooling; 0644 is appropriate.
				return err
			}
		}
	}
	return nil
}

func renderDetailedRationale(r *WizardResult) string {
	s := "# R1 Configuration Rationale\n\n"
	s += fmt.Sprintf("Generated: %s\n\n", r.GeneratedAt.Format("2006-01-02 15:04:05"))

	s += "## Maturity Assessment\n\n"
	s += fmt.Sprintf("- **Stage:** %s (score: %d/100)\n", r.Maturity.Stage, r.Maturity.Score)
	s += "- **Breakdown:**\n"
	for signal, score := range r.Maturity.Breakdown {
		s += fmt.Sprintf("  - %s: %d/100\n", signal, score)
	}
	s += "\n"

	s += "## Decisions\n\n"
	for _, e := range r.Rationale {
		s += fmt.Sprintf("### %s = %s\n", e.Field, e.Value)
		s += fmt.Sprintf("- **Source:** %s\n", e.Source)
		if e.Confidence > 0 {
			s += fmt.Sprintf("- **Confidence:** %.0f%%\n", e.Confidence*100)
		}
		if e.Evidence != "" {
			s += fmt.Sprintf("- **Evidence:** %s\n", e.Evidence)
		}
		s += "\n"
	}

	s += "## Skills Selected\n\n"
	for _, name := range r.Skills {
		s += fmt.Sprintf("- %s\n", name)
	}
	return s
}
