#!/usr/bin/env bash
# quality-audit.sh — audit every completed scope-suite run's output quality.
#
# Runs on each rung that has a terminal banner (SIMPLE LOOP COMPLETE /
# PARTIAL / ABORT / SOW finished). For each:
#   - commits (total, atomic-looking vs bundled)
#   - TS LOC + file count
#   - npm test (or pnpm test) exit status + test counts
#   - tsc --noEmit errors (if tsconfig exists)
#   - build command exit status (best-effort detection)
#   - H-27 hits, H-28 hits, total gate-hits
#
# Writes a markdown-table row per run to RESULTS.md's "Quality audit"
# section. Idempotent — skips runs already in RESULTS.md.

set -uo pipefail

SUITE=/home/eric/repos/stoke/plans/scope-suite
RUNS=/home/eric/repos/scope-suite-runs
RESULTS=$SUITE/RESULTS.md

declare -a rows
for dir in "$RUNS"/*-20260418T*; do
  [[ -d "$dir" ]] || continue
  name=$(basename "$dir")
  # Only audit terminal runs.
  terminal=$(grep -E "SIMPLE LOOP COMPLETE|SIMPLE LOOP PARTIAL|SIMPLE LOOP ABORTED|SOW finished" "$dir/stoke-run.log" 2>/dev/null | tail -1)
  [[ -n "$terminal" ]] || continue

  # Parse basics
  commits=$(git -C "$dir" rev-list --count HEAD 2>/dev/null)
  ts_files=$(git -C "$dir" ls-files '*.ts' '*.tsx' 2>/dev/null | wc -l | tr -d ' ')
  ts_loc=$(git -C "$dir" ls-files '*.ts' '*.tsx' 2>/dev/null | xargs -r wc -l 2>/dev/null | tail -1 | awk '{print $1}')
  ts_loc=${ts_loc:-0}
  gates=$(grep -cE "\[gate-hit\]" "$dir/stoke-run.log" 2>/dev/null)
  h27=$(grep -cE "declared-symbol-not-implemented[^-]" "$dir/stoke-run.log" 2>/dev/null)
  h28=$(grep -cE "declared-symbol-not-implemented-ts" "$dir/stoke-run.log" 2>/dev/null)

  # Test + tsc status
  test_status="n/a"
  if [[ -f "$dir/package.json" ]]; then
    if grep -q '"test"' "$dir/package.json" 2>/dev/null; then
      test_out=$(cd "$dir" && timeout 60 npm test 2>&1 | tail -30)
      if echo "$test_out" | grep -qE "passed|PASS"; then
        pass_count=$(echo "$test_out" | grep -oE "[0-9]+ passed" | head -1)
        fail_count=$(echo "$test_out" | grep -oE "[0-9]+ failed" | head -1)
        if [[ -n "$fail_count" ]]; then
          test_status="⚠ $pass_count / $fail_count"
        else
          test_status="✅ $pass_count"
        fi
      elif echo "$test_out" | grep -qE "error|Error|No tests found"; then
        test_status="❌ fail"
      else
        test_status="❓ unclear"
      fi
    fi
  fi

  tsc_status="n/a"
  if [[ -f "$dir/tsconfig.json" ]]; then
    tsc_out=$(cd "$dir" && timeout 30 npx --no tsc --noEmit 2>&1)
    err_count=$(echo "$tsc_out" | grep -cE "error TS[0-9]+")
    if [[ "$err_count" -eq 0 ]]; then
      tsc_status="✅ clean"
    else
      tsc_status="⚠ $err_count errors"
    fi
  fi

  # Extract terminal result + duration
  result=$(echo "$terminal" | grep -oE "SIMPLE LOOP [A-Z-]+|SOW finished")
  # Wall-clock: approximate from first and last log mtime
  start=$(head -1 "$dir/stoke-run.log" 2>/dev/null | head -c 40)
  end_line=$(tail -1 "$dir/stoke-run.log" 2>/dev/null | head -c 40)
  duration_s=$(( $(stat -c %Y "$dir/stoke-run.log") - $(stat -c %Y "$dir/SOW.md" 2>/dev/null || echo 0) ))
  duration_min=$(( duration_s / 60 ))m

  rows+=( "| $name | $result | ${duration_min} | $commits | $ts_files | $ts_loc | $test_status | $tsc_status | $gates/$h27/$h28 |" )
done

# Emit table (always replaces the section; cheap since rung count is small)
tmp=$(mktemp)
awk '/^## Quality audit/ {skip=1} /^## / && !/^## Quality audit/ {skip=0} !skip' "$RESULTS" > "$tmp"
{
  cat "$tmp"
  echo ""
  echo "## Quality audit"
  echo ""
  echo "Auto-generated by \`plans/scope-suite/quality-audit.sh\`. Run \`bash plans/scope-suite/quality-audit.sh\` to refresh."
  echo ""
  echo "| Run | Result | Duration | Commits | TS files | TS LOC | Tests | tsc | gates/H27/H28 |"
  echo "|---|---|---|---|---|---|---|---|---|"
  for row in "${rows[@]}"; do
    echo "$row"
  done
} > "$RESULTS"
rm -f "$tmp"

echo "Audited ${#rows[@]} terminal runs. Results in $RESULTS."
