// Package cortex — Lane value type and lifecycle.
//
// A "lane" is the per-surface-visible thread of activity inside a single r1d
// session: the main agent thread, a cortex Lobe, an in-flight tool call, or
// a mission-task. See specs/lanes-protocol.md §1 for the full taxonomy and
// §3 for the state machine.
//
// This file owns the cortex-side Lane value type. Wire-format event types
// live in internal/hub (EventLane*, LaneEvent, LaneStatus, LaneKind); this
// file emits those events through the in-process hub.Bus on every
// significant lifecycle transition.
package cortex

import (
	"time"

	"github.com/RelayOne/r1/internal/hub"
)

// Lane is the cortex-side value type representing one lane in the lanes
// protocol. It is constructed exclusively via Workspace.NewMainLane,
// Workspace.NewLobeLane, and Workspace.NewToolLane (TASK-6 in
// specs/lanes-protocol.md §11). Direct struct-literal construction is
// permitted only inside the cortex package and tests.
//
// Field set is fixed by spec §5 to {ID, Kind, ParentID, Label, Status,
// Pinned, StartedAt, EndedAt, LastSeq}. Adding a field is allowed
// (additive); renaming or removing one breaks the wire-format contract
// (LaneEvent shape) and requires a wire-version bump per spec §5.6.
//
// Concurrency: Lane is a value type. Mutators on *Lane (Transition, Kill,
// Emit*) take the workspace mutex; readers should grab a snapshot via
// Lane.Clone (TASK-6) before reading from outside the workspace.
type Lane struct {
	// ID is the lane's ULID. Generated by Workspace.NewLane* constructors;
	// stable for the lifetime of the lane.
	ID string

	// Kind names the lane category (main, lobe, tool, mission_task,
	// router). See specs/lanes-protocol.md §4.1.
	Kind hub.LaneKind

	// ParentID is the parent lane's ID. Empty for the main lane and for
	// top-level mission tasks per spec §4.1.
	ParentID string

	// Label is the human-readable label shown in surfaces (e.g.
	// "Recalling memories matching: 'cortex workspace'").
	Label string

	// Status is the current lifecycle state. The state machine is
	// validated by Lane.Transition per spec §3.3.
	Status hub.LaneStatus

	// Pinned is the orthogonal flag (does not change Status). Pinned
	// lanes render above unpinned ones across all surfaces.
	Pinned bool

	// StartedAt is the lane creation timestamp.
	StartedAt time.Time

	// EndedAt is the lane termination timestamp; zero for non-terminal
	// lanes.
	EndedAt time.Time

	// LastSeq is the most recent per-session seq emitted by this lane.
	// Updated on every event emission so r1.lanes.list can return it
	// without scanning the WAL.
	LastSeq uint64

	// deltaSeq is the per-lane content stream counter incremented on
	// each EmitDelta call. Distinct from session-wide LastSeq; lets the
	// surface detect intra-lane gaps independent of the session-wide
	// seq (spec §4.3). Atomic so EmitDelta does not need the workspace
	// mutex.
	deltaSeq uint64

	// workspace back-pointer used by Transition and Emit*. Unexported
	// because the public type is value-shaped; consumers should never
	// reach back into the workspace from a copy.
	ws *Workspace
}

// Clone returns a copy of the Lane suitable for hand-off across goroutine
// boundaries. The workspace back-pointer is preserved so Transition/Emit*
// continue to work on the clone, but mutating fields on the clone will not
// be observed by the workspace's canonical record.
//
// Use Clone only for snapshots emitted to surfaces; mutate the canonical
// Lane through Workspace methods.
func (l Lane) Clone() Lane {
	return l
}

// IsTerminal reports whether the lane is in one of the three terminal
// states (done, errored, cancelled). Convenience over Status.IsTerminal.
func (l Lane) IsTerminal() bool {
	return l.Status.IsTerminal()
}
